version: "3.9"
services:
  dev:
    build:
      context: "."
      dockerfile: Dockerfile-R
    ports:
      - 8889:8888
    volumes:
      - ./work:/work
    working_dir: /work
    entrypoint: jupyter notebook --no-browser --allow-root --ip 0.0.0.0 --port 8888
