version: "3"
services:
  jupyter:
    image: c2dhunilu/journal-of-digital-history-jupyter
    ports:
      - 8889:8888
    volumes:
      - ./work:/work
    working_dir: /work
    entrypoint: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --port 8888
